name: Run Tests on Push

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: |
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start Laravel Sail
        run: |
          sudo chmod +x vendor/bin/sail
          ./vendor/bin/sail up -d

      - name: Generate application key
        run: |
          ./vendor/bin/sail artisan key:generate

      - name: Run Database Migrations
        run: |
          ./vendor/bin/sail artisan migrate --force

      - name: Run PHPUnit Tests
        run: |
          ./vendor/bin/sail test

      - name: Stop Laravel Sail
        run: |
          ./vendor/bin/sail down
