name: Run Tests on Push

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    services:
      laravel.test:
        image: sail-8.2/app
        ports:
          - '80:80'
          - '5173:5173'
        environment:
          WWWUSER: '${{ secrets.WWWUSER }}'
          WWWGROUP: '${{ secrets.WWWGROUP }}'
          DB_DATABASE: '${{ secrets.DB_DATABASE }}'
          DB_USERNAME: '${{ secrets.DB_USERNAME }}'
          DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'
          SAIL_XDEBUG_MODE: '${{ secrets.SAIL_XDEBUG_MODE }}'
          SAIL_XDEBUG_CONFIG: 'client_host=host.docker.internal'
        volumes:
          - '.:/var/www/html'
        networks:
          - sail

      mysql:
        image: mysql/mysql-server:8.0
        ports:
          - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: '${{ secrets.DB_PASSWORD }}'
          MYSQL_DATABASE: '${{ secrets.DB_DATABASE }}'
          MYSQL_USER: '${{ secrets.DB_USERNAME }}'
          MYSQL_PASSWORD: '${{ secrets.DB_PASSWORD }}'
        volumes:
          - 'sail-mysql:/var/lib/mysql'
        networks:
          - sail
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Laravel Sail
        run: |
          sudo chmod +x vendor/laravel/sail/runtimes/8.2/vendor/bin/sail
          vendor/laravel/sail/runtimes/8.2/vendor/bin/sail up -d

      - name: Install Composer dependencies
        run: |
          vendor/laravel/sail/runtimes/8.2/vendor/bin/sail composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate application key
        run: |
          vendor/laravel/sail/runtimes/8.2/vendor/bin/sail artisan key:generate

      - name: Run Database Migrations
        run: |
          vendor/laravel/sail/runtimes/8.2/vendor/bin/sail artisan migrate --force

      - name: Run PHPUnit Tests
        run: |
          vendor/laravel/sail/runtimes/8.2/vendor/bin/sail test

      - name: Stop Laravel Sail
        run: |
          vendor/laravel/sail/runtimes/8.2/vendor/bin/sail down
